apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-replacer-example-secret
data:
  sample-secret: {{ .Values.secret.sampleSecret | b64enc }}
  sample-secret-quoted: {{ .Values.secret.sampleSecretQuoted | b64enc | quote }}
type: Opaque
